name: Release https://lrc-maker.github.io and npm

on:
    push:
        tags:
            - "v*"

jobs:
    deploy:
        if: startsWith(github.ref, 'refs/tags/v')
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: ".node-version"

            - name: Install dependencies
              uses: pnpm/action-setup@v2
              with:
                  run_install: |
                      - args: [--frozen-lockfile, --strict-peer-dependencies]

            - run: pnpm run "/check\:/"
            - run: pnpm run build

            - name: Deploy to lrc-maker.github.io
              uses: peaceiris/actions-gh-pages@v3
              with:
                  personal_token: ${{ secrets.GHP_TOKEN }}
                  external_repository: lrc-maker/lrc-maker.github.io
                  publish_branch: master
                  publish_dir: ./build
                  force_orphan: true
